<a href="https://colab.research.google.com/github/pooja251096/Rossmann-Sales-Prediction-/blob/main/Rossmann_Sales_Prediction_Capstone_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <b><u> Project Title : Sales Prediction : Predicting sales of a major store chain Rossmann</u></b>

## <b> Problem Description </b>

### Rossmann operates over 3,000 drug stores in 7 European countries. Currently, Rossmann store managers are tasked with predicting their daily sales for up to six weeks in advance. Store sales are influenced by many factors, including promotions, competition, school and state holidays, seasonality, and locality. With thousands of individual managers predicting sales based on their unique circumstances, the accuracy of results can be quite varied.

### You are provided with historical sales data for 1,115 Rossmann stores. The task is to forecast the "Sales" column for the test set. Note that some stores in the dataset were temporarily closed for refurbishment.

## <b> Data Description </b>

### <b>Rossmann Stores Data.csv </b> - historical data including Sales
### <b>store.csv </b> - supplemental information about the stores


### <b><u>Data fields</u></b>
### Most of the fields are self-explanatory. The following are descriptions for those that aren't.

* #### Id - an Id that represents a (Store, Date) duple within the test set
* #### Store - a unique Id for each store
* #### Sales - the turnover for any given day (this is what you are predicting)
* #### Customers - the number of customers on a given day
* #### Open - an indicator for whether the store was open: 0 = closed, 1 = open
* #### StateHoliday - indicates a state holiday. Normally all stores, with few exceptions, are closed on state holidays. Note that all schools are closed on public holidays and weekends. a = public holiday, b = Easter holiday, c = Christmas, 0 = None
* #### SchoolHoliday - indicates if the (Store, Date) was affected by the closure of public schools
* #### StoreType - differentiates between 4 different store models: a, b, c, d
* #### Assortment - describes an assortment level: a = basic, b = extra, c = extended
* #### CompetitionDistance - distance in meters to the nearest competitor store
* #### CompetitionOpenSince[Month/Year] - gives the approximate year and month of the time the nearest competitor was opened
* #### Promo - indicates whether a store is running a promo on that day
* #### Promo2 - Promo2 is a continuing and consecutive promotion for some stores: 0 = store is not participating, 1 = store is participating
* #### Promo2Since[Year/Week] - describes the year and calendar week when the store started participating in Promo2
* #### PromoInterval - describes the consecutive intervals Promo2 is started, naming the months the promotion is started anew. E.g. "Feb,May,Aug,Nov" means each round starts in February, May, August, November of any given year for that store

In [87]:
# Importing the libraries
import numpy as np
import pandas as pd
from numpy import math

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

import matplotlib.pyplot as plt
import seaborn as sns
import calendar
import datetime

In [88]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [89]:
store_data = pd.read_csv('/content/drive/MyDrive/Almabetter learning/Retail sales prediction/Rossmann Stores Data.csv')
stores = pd.read_csv('/content/drive/MyDrive/Almabetter learning/Retail sales prediction/store.csv')

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (7) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [90]:
store_data.head()

Store  DayOfWeek        Date  Sales  ...  Open  Promo  StateHoliday SchoolHoliday
0      1          5  2015-07-31   5263  ...     1      1             0             1
1      2          5  2015-07-31   6064  ...     1      1             0             1
2      3          5  2015-07-31   8314  ...     1      1             0             1
3      4          5  2015-07-31  13995  ...     1      1             0             1
4      5          5  2015-07-31   4822  ...     1      1             0             1

[5 rows x 9 columns]

In [91]:
## Convert date column from object to date
store_data['Date']= pd.to_datetime(store_data['Date'])

In [92]:
store_data['Year'] = pd.DatetimeIndex(store_data['Date']).year
store_data['Month'] = pd.DatetimeIndex(store_data['Date']).month

In [93]:
store_data.head()

Store  DayOfWeek       Date  Sales  ...  StateHoliday  SchoolHoliday  Year Month
0      1          5 2015-07-31   5263  ...             0              1  2015     7
1      2          5 2015-07-31   6064  ...             0              1  2015     7
2      3          5 2015-07-31   8314  ...             0              1  2015     7
3      4          5 2015-07-31  13995  ...             0              1  2015     7
4      5          5 2015-07-31   4822  ...             0              1  2015     7

[5 rows x 11 columns]

In [94]:
stores.isna().sum()

Store                          0
StoreType                      0
Assortment                     0
CompetitionDistance            3
CompetitionOpenSinceMonth    354
CompetitionOpenSinceYear     354
Promo2                         0
Promo2SinceWeek              544
Promo2SinceYear              544
PromoInterval                544
dtype: int64

In [95]:
## Wherever Promo2 ie continuing and consecutive promotion is zero, implies store didn't participate,
# hence Promo2SinceWeek and Promo2SinceYear should be zero, also there won't be PromoInterval
stores.loc[(stores['Promo2']==0) & (stores['Promo2SinceWeek'].isna()),['Promo2SinceWeek']]=0
stores.loc[(stores['Promo2']==0) & (stores['Promo2SinceYear'].isna()),['Promo2SinceYear','PromoInterval']]=0

In [96]:
stores.loc[stores['CompetitionDistance'].isna()]=stores['CompetitionDistance'].max()#CompetitionDistance

In [97]:
stores.isna().sum()

Store                          0
StoreType                      0
Assortment                     0
CompetitionDistance            0
CompetitionOpenSinceMonth    351
CompetitionOpenSinceYear     351
Promo2                         0
Promo2SinceWeek                0
Promo2SinceYear                0
PromoInterval                  0
dtype: int64

In [98]:
## CompetitionOpenSinceMonth and CompetitionOpenSinceYear have been combined, 
## so no changes in individual columns, 
## in the final data set both have been dropped

In [99]:
store_data['Date'].min()

Timestamp('2013-01-01 00:00:00')

In [100]:
stores[stores['Promo2SinceYear']!=0]['Promo2SinceYear'].min()

2009.0

In [101]:
### Code Ref https://www.kaggle.com/shivam017arora/rossmann-sales-prediction-top-1-solution
## Modified accordingly

competition_open = []
for index, value in stores[['CompetitionOpenSinceMonth', 'CompetitionOpenSinceYear']].iterrows():
    try:
        year, month = int(value['CompetitionOpenSinceYear']), int(value['CompetitionOpenSinceMonth'])
        date = pd.to_datetime("{}-{}-01".format(year, month), format='%Y-%m')
        competition_open.append(date)
    except:
        competition_open.append('1813-01-01') # Added a dummy date, 200 yrs less than min sales date
stores['CompetitionOpen'] = pd.Series(competition_open)
stores['CompetitionOpen'] = stores['CompetitionOpen'].dt.strftime('%Y-%m-%d')
stores['CompetitionOpen']= pd.to_datetime(stores['CompetitionOpen'])





promo = []
for index, value in stores[['Promo2SinceWeek', 'Promo2SinceYear']].iterrows():
    try:
        year, week = int(value['Promo2SinceYear']), int(value['Promo2SinceWeek'])
        date = pd.to_datetime("{}{}0".format(year, week), format='%Y%W%w')
        promo.append(date)
    except:
        promo.append('1909-01-01')   ## dummy date
stores['promoYearWeek'] = pd.to_datetime(pd.Series(promo))
stores['promoYearWeek'] = stores['promoYearWeek'].dt.strftime('%Y%m%d')
stores['promoYearWeek']= pd.to_datetime(stores['promoYearWeek'])


In [102]:
stores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1115 entries, 0 to 1114
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype         
---  ------                     --------------  -----         
 0   Store                      1115 non-null   int64         
 1   StoreType                  1115 non-null   object        
 2   Assortment                 1115 non-null   object        
 3   CompetitionDistance        1115 non-null   float64       
 4   CompetitionOpenSinceMonth  764 non-null    float64       
 5   CompetitionOpenSinceYear   764 non-null    float64       
 6   Promo2                     1115 non-null   int64         
 7   Promo2SinceWeek            1115 non-null   float64       
 8   Promo2SinceYear            1115 non-null   float64       
 9   PromoInterval              1115 non-null   object        
 10  CompetitionOpen            1115 non-null   datetime64[ns]
 11  promoYearWeek              1115 non-null   datetime64[ns]
dtypes: dat

In [103]:
stores.head()

Store StoreType Assortment  ...    PromoInterval  CompetitionOpen  promoYearWeek
0      1         c          a  ...                0       2008-09-01     1909-01-01
1      2         a          a  ...  Jan,Apr,Jul,Oct       2007-11-01     2010-04-04
2      3         a          a  ...  Jan,Apr,Jul,Oct       2006-12-01     2011-04-10
3      4         c          c  ...                0       2009-09-01     1909-01-01
4      5         a          a  ...                0       2015-04-01     1909-01-01

[5 rows x 12 columns]

In [104]:
store_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1017209 entries, 0 to 1017208
Data columns (total 11 columns):
 #   Column         Non-Null Count    Dtype         
---  ------         --------------    -----         
 0   Store          1017209 non-null  int64         
 1   DayOfWeek      1017209 non-null  int64         
 2   Date           1017209 non-null  datetime64[ns]
 3   Sales          1017209 non-null  int64         
 4   Customers      1017209 non-null  int64         
 5   Open           1017209 non-null  int64         
 6   Promo          1017209 non-null  int64         
 7   StateHoliday   1017209 non-null  object        
 8   SchoolHoliday  1017209 non-null  int64         
 9   Year           1017209 non-null  int64         
 10  Month          1017209 non-null  int64         
dtypes: datetime64[ns](1), int64(9), object(1)
memory usage: 85.4+ MB


In [105]:
store_data_merged=pd.merge(store_data,stores,on='Store')

In [106]:
store_data_merged['day_diff_comp']=(store_data_merged['Date']-store_data_merged['CompetitionOpen']).dt.days
store_data_merged['day_diff_promo']=(store_data_merged['Date']-store_data_merged['promoYearWeek']).dt.days
store_data_merged.loc[store_data_merged['day_diff_comp']>=73000,'day_diff_comp']=0
store_data_merged.loc[store_data_merged['day_diff_promo']>=36500,'day_diff_promo']=0

In [107]:
store_data_merged.drop(columns=['CompetitionOpenSinceYear','CompetitionOpenSinceMonth','Promo2SinceWeek','Promo2SinceYear','PromoInterval','CompetitionOpen','promoYearWeek'],inplace=True)

In [108]:
#store_data.drop(columns='Date',inplace=True)
store_data_merged.head()

Store  DayOfWeek       Date  ...  Promo2  day_diff_comp  day_diff_promo
0      1          5 2015-07-31  ...       0           2524               0
1      1          4 2015-07-30  ...       0           2523               0
2      1          3 2015-07-29  ...       0           2522               0
3      1          2 2015-07-28  ...       0           2521               0
4      1          1 2015-07-27  ...       0           2520               0

[5 rows x 17 columns]

In [109]:
store_data_merged.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1014567 entries, 0 to 1014566
Data columns (total 17 columns):
 #   Column               Non-Null Count    Dtype         
---  ------               --------------    -----         
 0   Store                1014567 non-null  int64         
 1   DayOfWeek            1014567 non-null  int64         
 2   Date                 1014567 non-null  datetime64[ns]
 3   Sales                1014567 non-null  int64         
 4   Customers            1014567 non-null  int64         
 5   Open                 1014567 non-null  int64         
 6   Promo                1014567 non-null  int64         
 7   StateHoliday         1014567 non-null  object        
 8   SchoolHoliday        1014567 non-null  int64         
 9   Year                 1014567 non-null  int64         
 10  Month                1014567 non-null  int64         
 11  StoreType            1014567 non-null  object        
 12  Assortment           1014567 non-null  object        
 1

In [110]:
store_data_merged['CompetitionDistance']=store_data_merged['CompetitionDistance'].astype(int)

In [111]:
store_data_merged['Assortment']=store_data_merged['Assortment'].apply(lambda x: 1 if x=='a' else (2 if x=='b' else 3))

In [112]:
store_data_final=pd.get_dummies(store_data_merged,drop_first=True)

In [113]:
store_data_final.isna().sum()


Store                  0
DayOfWeek              0
Date                   0
Sales                  0
Customers              0
Open                   0
Promo                  0
SchoolHoliday          0
Year                   0
Month                  0
Assortment             0
CompetitionDistance    0
Promo2                 0
day_diff_comp          0
day_diff_promo         0
StateHoliday_0         0
StateHoliday_a         0
StateHoliday_b         0
StateHoliday_c         0
StoreType_b            0
StoreType_c            0
StoreType_d            0
dtype: int64

In [114]:
store_data_final.drop(columns=['Date'],inplace=True) ## Dropping Date column as month and year have been extracted

In [115]:
############ Final Data

In [116]:
store_data_final

Store  DayOfWeek  Sales  ...  StoreType_b  StoreType_c  StoreType_d
0            1          5   5263  ...            0            1            0
1            1          4   5020  ...            0            1            0
2            1          3   4782  ...            0            1            0
3            1          2   5011  ...            0            1            0
4            1          1   6102  ...            0            1            0
...        ...        ...    ...  ...          ...          ...          ...
1014562   1115          6   4771  ...            0            0            1
1014563   1115          5   4540  ...            0            0            1
1014564   1115          4   4297  ...            0            0            1
1014565   1115          3   3697  ...            0            0            1
1014566   1115          2      0  ...            0            0            1

[1014567 rows x 21 columns]

In [117]:
np.all(np.isfinite(store_data_final))

True

In [118]:
np.any(np.isnan(store_data_final))

False

In [121]:
store_data_final.to_csv('sample.csv')
#from google.colab import files
#files.download("sample4.csv")

In [122]:
dataset = pd.read_csv('sample.csv')


In [123]:
dataset.columns

Index(['Unnamed: 0', 'Store', 'DayOfWeek', 'Sales', 'Customers', 'Open',
       'Promo', 'SchoolHoliday', 'Year', 'Month', 'Assortment',
       'CompetitionDistance', 'Promo2', 'day_diff_comp', 'day_diff_promo',
       'StateHoliday_0', 'StateHoliday_a', 'StateHoliday_b', 'StateHoliday_c',
       'StoreType_b', 'StoreType_c', 'StoreType_d'],
      dtype='object')

In [124]:
dataset = dataset[['Store', 'DayOfWeek', 'Customers', 'Open',
       'Promo', 'SchoolHoliday', 'Year', 'Month', 'Assortment',
       'CompetitionDistance', 'Promo2', 'day_diff_comp', 'day_diff_promo',
       'StateHoliday_0', 'StateHoliday_a', 'StateHoliday_b', 'StateHoliday_c',
       'StoreType_b', 'StoreType_c', 'StoreType_d', 'Sales']]

In [125]:
dataset.fillna(0)

Store  DayOfWeek  Customers  ...  StoreType_c  StoreType_d  Sales
0            1          5        555  ...            1            0   5263
1            1          4        546  ...            1            0   5020
2            1          3        523  ...            1            0   4782
3            1          2        560  ...            1            0   5011
4            1          1        612  ...            1            0   6102
...        ...        ...        ...  ...          ...          ...    ...
1014562   1115          6        339  ...            0            1   4771
1014563   1115          5        326  ...            0            1   4540
1014564   1115          4        300  ...            0            1   4297
1014565   1115          3        305  ...            0            1   3697
1014566   1115          2          0  ...            0            1      0

[1014567 rows x 21 columns]

In [126]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [127]:
#Splitting the data into train and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 42 )

In [128]:
print(X_train)

[[ 574    4  565 ...    0    0    1]
 [1084    3  690 ...    0    0    0]
 [ 239    1  267 ...    0    0    1]
 ...
 [ 146    3  578 ...    0    0    1]
 [ 740    4  527 ...    0    0    1]
 [ 134    6  287 ...    0    0    0]]


In [129]:
print(y_train)

[6935 4849 2935 ... 5349 7441 2963]


In [130]:
print(X_test)

[[ 851    6  494 ...    0    0    1]
 [ 412    2  454 ...    0    0    1]
 [ 281    1  410 ...    0    0    1]
 ...
 [ 821    3  909 ...    0    0    0]
 [ 363    5  884 ...    0    0    0]
 [1020    3 1108 ...    0    0    0]]


In [131]:
print(y_test)

[5337 5451 3968 ... 7876 6887 9505]


In [132]:

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [133]:
print(X_train)

[[ 4.82271168e-02  5.36190247e-04 -1.47076072e-01 ... -1.25813368e-01
  -3.94905255e-01  1.50437815e+00]
 [ 1.63141343e+00 -5.00077999e-01  1.22072981e-01 ... -1.25813368e-01
  -3.94905255e-01 -6.64726487e-01]
 [-9.91708992e-01 -1.50130638e+00 -7.88727415e-01 ... -1.25813368e-01
  -3.94905255e-01  1.50437815e+00]
 ...
 [-1.28040767e+00 -5.00077999e-01 -1.19084571e-01 ... -1.25813368e-01
  -3.94905255e-01  1.50437815e+00]
 [ 5.63538741e-01  5.36190247e-04 -2.28897384e-01 ... -1.25813368e-01
  -3.94905255e-01  1.50437815e+00]
 [-1.31765912e+00  1.00176457e+00 -7.45663566e-01 ... -1.25813368e-01
  -3.94905255e-01 -6.64726487e-01]]


In [134]:
print(X_test)

[[ 0.90811459  1.00176457 -0.29995273 ... -0.12581337 -0.39490525
   1.50437815]
 [-0.45466736 -1.00069219 -0.38608043 ... -0.12581337 -0.39490525
   1.50437815]
 [-0.86132894 -1.50130638 -0.4808209  ... -0.12581337 -0.39490525
   1.50437815]
 ...
 [ 0.81498598 -0.500078    0.59362212 ... -0.12581337 -0.39490525
  -0.66472649]
 [-0.60677742  0.50115038  0.53979231 ... -0.12581337 -0.39490525
  -0.66472649]
 [ 1.43273907 -0.500078    1.02210742 ... -0.12581337 -0.39490525
  -0.66472649]]


In [135]:
#Fitting KNN Model
from sklearn.neighbors import KNeighborsRegressor
regressor = KNeighborsRegressor(n_neighbors=5, weights='uniform', algorithm='auto', leaf_size=30, p=2, metric='minkowski', metric_params=None, n_jobs=-1)
regressor.fit(X_train, y_train)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
                    weights='uniform')

In [136]:
#Predicting the test values with model
y_pred = regressor.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))


[[5364.8 5337. ]
 [5419.8 5451. ]
 [4183.  3968. ]
 ...
 [7788.8 7876. ]
 [7679.8 6887. ]
 [9905.4 9505. ]]


In [137]:
#checking R2 Score
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9525637413597642